//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bracket.Samples.AppAutomation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("context.Alert(\"Hello from Ruby! You Clicked \'Do Something\'\")")]
        public string btnDoSomething_Click_Handler {
            get {
                return ((string)(this["btnDoSomething_Click_Handler"]));
            }
            set {
                this["btnDoSomething_Click_Handler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Hello from Ruby! You Clicked \'Do Something Else!\'\"")]
        public string btnDoSomethingElse_Click_Handler {
            get {
                return ((string)(this["btnDoSomethingElse_Click_Handler"]));
            }
            set {
                this["btnDoSomethingElse_Click_Handler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"You typed #{context.sender.text}\"")]
        public string txtTypeHere_Validated_Handler {
            get {
                return ((string)(this["txtTypeHere_Validated_Handler"]));
            }
            set {
                this["txtTypeHere_Validated_Handler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtTypeHere_Validating_Handler {
            get {
                return ((string)(this["txtTypeHere_Validating_Handler"]));
            }
            set {
                this["txtTypeHere_Validating_Handler"] = value;
            }
        }
    }
}
