//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bracket.Hosting.Samples.Embedded.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Service")]
        public string AzureServiceBusServiceNamespace {
            get {
                return ((string)(this["AzureServiceBusServiceNamespace"]));
            }
            set {
                this["AzureServiceBusServiceNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Secret")]
        public string AzureServiceBusIssuerSecret {
            get {
                return ((string)(this["AzureServiceBusIssuerSecret"]));
            }
            set {
                this["AzureServiceBusIssuerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bracket")]
        public string AzureServiceBusServicePath {
            get {
                return ((string)(this["AzureServiceBusServicePath"]));
            }
            set {
                this["AzureServiceBusServicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AzureServiceBusUseSSL {
            get {
                return ((bool)(this["AzureServiceBusUseSSL"]));
            }
            set {
                this["AzureServiceBusUseSSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("owner")]
        public string AzureServiceBusIssuerName {
            get {
                return ((string)(this["AzureServiceBusIssuerName"]));
            }
            set {
                this["AzureServiceBusIssuerName"] = value;
            }
        }
    }
}
